import 'dotenv/config';
import express from 'express';

const app = express();
const port = process.env.PORT || 3000;
const ollamaBaseUrl = process.env.OLLAMA_BASE_URL || 'http://127.0.0.1:11434';
const ollamaModel = process.env.OLLAMA_MODEL || 'llama3.1:8b';

async function rewriteWithOllama(prompt) {
  const response = await fetch(`${ollamaBaseUrl}/api/generate`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      model: ollamaModel,
      prompt,
      stream: false,
    }),
  });

  if (!response.ok) {
    const details = await response.text();
    const error = new Error(`Ollama request failed with status ${response.status}`);
    error.status = response.status;
    error.details = details;
    throw error;
  }

  const data = await response.json();

  if (!data.response || typeof data.response !== 'string') {
    const error = new Error('Ollama returned an empty response.');
    error.status = 502;
    throw error;
  }

  return data.response.trim();
}

function formatOllamaError(err) {
  const status = Number(err?.status || 500);

  if (status === 404) {
    return {
      status: 502,
      error: `Ollama model \"${ollamaModel}\" is not available locally. Run \"ollama pull ${ollamaModel}\" and try again.`,
    };
  }

  if (err?.cause?.code === 'ECONNREFUSED' || /fetch failed/i.test(String(err?.message))) {
    return {
      status: 503,
      error: 'Ollama is not reachable. Start Ollama and confirm it is listening on OLLAMA_BASE_URL.',
    };
  }

  return {
    status: 500,
    error: 'Failed to rewrite text due to an Ollama error.',
  };
}

app.use(express.json());
app.use(express.static('public'));

app.post('/rewrite', async (req, res) => {
  const { text, tone } = req.body;

  if (!text || typeof text !== 'string' || text.trim().length === 0) {
    return res.status(400).json({ error: 'text is required' });
  }

  const toneClause = tone ? ` The tone should be ${tone}.` : '';

  const prompt = `You are a human editor. Rewrite the following text so it reads as if written naturally by a person — not generated by AI.${toneClause}

Rules:
- Use varied sentence lengths: mix short punchy sentences with longer ones.
- Avoid corporate or AI-sounding phrases like "delve into", "it's worth noting", "in today's world", "leverage", "utilize", "seamlessly", "game-changer", "cutting-edge", "robust", "ensure", "crucial", "I'd be happy to", "certainly", "absolutely", or any overly enthusiastic openers.
- Don't use bullet points or headers unless the original text had them.
- Preserve the original meaning and factual content exactly.
- Sound like a real person wrote it: slight informality is fine, contractions are welcome, opinions can feel direct.
- Never start the response with a meta-comment like "Here is..." or "Sure, here's...". Just output the rewritten text.

Text:
${text}`;

  try {
    const result = await rewriteWithOllama(prompt);
    res.json({ result });
  } catch (err) {
    console.error('Ollama error:', err);
    const clientError = formatOllamaError(err);
    res.status(clientError.status).json({ error: clientError.error });
  }
});

app.listen(port, () => {
  console.log(`Ollama base URL: ${ollamaBaseUrl}`);
  console.log(`Ollama model: ${ollamaModel}`);
  console.log(`Text Rewriter running at http://localhost:${port}`);
});
