import 'dotenv/config';
import express from 'express';
import { GoogleGenAI } from '@google/genai';

const app = express();
const port = process.env.PORT || 3000;

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

app.use(express.json());
app.use(express.static('public'));

app.post('/rewrite', async (req, res) => {
  const { text, tone } = req.body;

  if (!text || typeof text !== 'string' || text.trim().length === 0) {
    return res.status(400).json({ error: 'text is required' });
  }

  const toneClause = tone ? ` The tone should be ${tone}.` : '';

  const prompt = `You are a human editor. Rewrite the following text so it reads as if written naturally by a person — not generated by AI.${toneClause}

Rules:
- Use varied sentence lengths: mix short punchy sentences with longer ones.
- Avoid corporate or AI-sounding phrases like "delve into", "it's worth noting", "in today's world", "leverage", "utilize", "seamlessly", "game-changer", "cutting-edge", "robust", "ensure", "crucial", "I'd be happy to", "certainly", "absolutely", or any overly enthusiastic openers.
- Don't use bullet points or headers unless the original text had them.
- Preserve the original meaning and factual content exactly.
- Sound like a real person wrote it: slight informality is fine, contractions are welcome, opinions can feel direct.
- Never start the response with a meta-comment like "Here is..." or "Sure, here's...". Just output the rewritten text.

Text:
${text}`;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.0-flash',
      contents: prompt,
    });

    res.json({ result: response.text });
  } catch (err) {
    console.error('Gemini error:', err);
    res.status(500).json({ error: 'Failed to rewrite text. Check your API key and try again.' });
  }
});

app.listen(port, () => {
  console.log(`Text Rewriter running at http://localhost:${port}`);
});
